### ISSUE TITLE
How do I hit the redis cache in the docker-compose?

### ISSUE THREAD

**Issue by jacknugent** [jacknugent/pulse-tracker-server#5]
When I run `docker-compose up` I am able to hit `localhost:3000` and get back the node API -- just like when I run locally. However, I _cannot_ hit the redis-cache on any port. Where do I hit? What do I need to change?

**Comment by kateerogers** [comment]
@jacknugent I am looking into this now. I am running on windows, so I will have to use the docker container

**Comment by jacknugent** [comment]
@kateerogers thanks for helping out! Bummer you can't run locally to see the intended behavior.

You not having mac/linux reminded me of another problem -- what's the best way to test that a port is successfully running a redis cache? When I was running redis locally, I would just connect to the redis port using a [front-end](https://github.com/jacknugent/pulse-tracker-front-end)

If you run `curl localhost:<port>` on a redis port it returns nothing (but no error!). That's the best test I have right now besides attaching a front-end.

I will be looking into this problem later tonight (in probably 1.5 hours). I'm going to experiment with different docker-compose configurations, starting with [this one](https://stackoverflow.com/questions/49966097/running-redis-on-nodejs-docker-image).

**Comment by jacknugent** [comment]
I was totally misguided. I don't need to hit the redis cache -- I need to hit the websocket! Resolved by adding a port to listen for the websocket. Piece of cake.
